USE webDevelopment;
CREATE TABLE languagess
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    language VARCHAR(100)
);
CREATE TABLE tools
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    tools VARCHAR(100)
);
CREATE TABLE libraries
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    libraries VARCHAR(100)
);
CREATE TABLE ide
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ide VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS frameworks
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    frameworks VARCHAR(100)
);
DROP TABLE IF EXISTS tools;
DROP TABLE libraries;
DROP TABLE ide;
